# Game fps lock
GAME_FPS_LOCK = 120

# GUI
GAME_DEFAULT_GUI_SIZE = (280, 80)
GAME_DEFAULT_GUI_SPACING = 5

# Ball values
BALL_DEFAULT_COLOR = (255, 0, 0, 255)
BALL_DEFAULT_RADIUS = 10
BALL_DEFAULT_SPEED_MULTIPLIER = 20

# Grid values
GRID_DEFAULT_START = 8
GRID_DEFAULT_STOP = 20

# Player values
PLAYER_DEFAULT_DAMAGE = 1
PLAYER_DEFAULT_HEALTH = 3
PLAYER_DEFAULT_SCORE = 10000
PLAYER_DEFAULT_SIZE = (250, 20)
PLAYER_DEFAULT_SPEED = 500

# Wall values
HOLLOW_BOX_DEFAULT_WIDTH = 10